name: Release

on:
  push:
    tags:
    - 'v*'
    - 't*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t ./...

      - name: Set env
        run: |
         echo "GO111MODULE=on" >> $GITHUB_ENV
         # Release tag comes from the github reference.
         RELEASE_TAG=$(echo ${GITHUB_REF} | sed -e 's!.*/!!')
         echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
         echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_OUTPUT
         # Ensure the release tag has expected format.
         echo ${RELEASE_TAG} | grep -q '^[vt]' || exit 1
         # Release version is same as release tag without leading 'v'.
         RELEASE_VERSION=$(echo ${GITHUB_REF} | sed -e 's!.*/[vt]!!')
         echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
         echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Compile linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/wealdtech/ethereal/cmd.ReleaseVersion=${RELEASE_VERSION}"
          tar zcf ethereal-${RELEASE_VERSION}-linux-amd64.tar.gz ethereal
          sha256sum ethereal-${RELEASE_VERSION}-linux-amd64.tar.gz >ethereal-${RELEASE_VERSION}-linux-amd64.tar.gz.sha256

      - name: Compile linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/wealdtech/ethereal/cmd.ReleaseVersion=${RELEASE_VERSION}"
          tar zcf ethereal-${RELEASE_VERSION}-linux-arm64.tar.gz ethereal
          sha256sum ethereal-${RELEASE_VERSION}-linux-arm64.tar.gz >ethereal-${RELEASE_VERSION}-linux-arm64.tar.gz.sha256

      - name: Compile windows
        run: |
          GOOS=windows GOARCH=amd64 go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/wealdtech/ethereal/cmd.ReleaseVersion=${RELEASE_VERSION}"
          zip --junk-paths ethereal-${RELEASE_VERSION}-windows-exe.zip ethereal.exe
          sha256sum ethereal-${RELEASE_VERSION}-windows-exe.zip >ethereal-${RELEASE_VERSION}-windows-exe.zip.sha256

      - name: Compile osx AMD64
        run: |
          GOOS=darwin GOARCH=amd64 go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/wealdtech/ethereal/cmd.ReleaseVersion=${RELEASE_VERSION}"
          tar zcf ethereal-${RELEASE_VERSION}-darwin-amd64.tar.gz ethereal
          sha256sum ethereal-${RELEASE_VERSION}-darwin-amd64.tar.gz >ethereal-${RELEASE_VERSION}-darwin-amd64.tar.gz.sha256

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: false
          files: |
            ethereal-${RELEASE_VERSION}-linux-amd64.tar.gz
            ethereal-${RELEASE_VERSION}-linux-amd64.tar.gz.sha256
            ethereal-${RELEASE_VERSION}-linux-arm64.tar.gz
            ethereal-${RELEASE_VERSION}-linux-arm64.tar.gz.sha256
            ethereal-${RELEASE_VERSION}-windows-exe.zip
            ethereal-${RELEASE_VERSION}-windows-exe.zip.sha256
            ethereal-${RELEASE_VERSION}-darwin-amd64.tar.gz
            ethereal-${RELEASE_VERSION}-darwin-amd64.tar.gz.sha256
