name: Release

on:
  push:
    tags:
    - 'v*'
    - 't*'

jobs:
  # Set variables that will be available to all builds.
  vars:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.release_version }}
      binary: ${{ steps.binary.outputs.binary }}
    steps:
      - id: release_version
        run: |
          RELEASE_VERSION=$(echo ${{ github.ref_name }} | sed -e 's/^[vt]//')
          echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
      - id: binary
        run: |
          BINARY=$(basename ${{ github.repository }})
          echo "binary=$(BINARY}" >> $GITHUB_OUTPUT

  # Create a github release to hold the assets once built.
  create_release:
    runs-on: ubuntu-latest
    needs: vars
    outputs:
      upload_url: ${{ steps.release_action.outputs.upload_url }}
    steps:
      - name: Create Release
        id: release_action
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ needs.vars.outputs.release_version }}
          draft: true
          prerelease: false

  # Build and pack the binaries for linux.
  build_linux:
    runs-on: ubuntu-latest
    needs: [create_release, vars]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out repository into the Go module directory
        uses: actions/checkout@v3

      - name: Select correct tag
        run: git checkout ${{ github.ref_name }}

      - name: Fetch repository dependencies
        run: go get -v -t ./...

      - name: Compile
        run: |
          go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/${{ github.repository }}/cmd.ReleaseVersion=${{ needs.vars.outputs.release_version }}"
          tar zcf ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz ${{ needs.vars.outputs.binary }}
          sha256sum ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz | sed -e 's/ .*//' >${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz.sha256
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        vars:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload hash
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz.sha256
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-amd64.tar.gz.sha256
          asset_content_type: text/plain

      - name: Cross compile (ARM64)
        run: |
          GOOS=linux GOARCH=arm64 go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/${{ github.repository }}/cmd.ReleaseVersion=${{ needs.vars.outputs.release_version }}"
          tar zcf ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz ${{ needs.vars.outputs.binary }}
          sha256sum ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz | sed -e 's/ .*//' >${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz.sha256

      - name: Upload binary (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload hash (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz.sha256
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-linux-arm64.tar.gz.sha256
          asset_content_type: text/plain

  # Build and pack the binaries for OSX.
  build_macos:
    runs-on: macos-latest
    needs: [create_release, vars]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out repository into the Go module directory
        uses: actions/checkout@v3

      - name: Select correct tag
        run: git checkout ${{ github.ref_name }}

      - name: Fetch repository dependencies
        run: go get -v -t ./...

      - name: Compile
        run: |
          go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/${{ github.repository }}/cmd.ReleaseVersion=${{ needs.vars.outputs.release_version }}"
          tar zcf ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz ${{ needs.vars.outputs.binary }}
          brew install coreutils
          sha256sum ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz | sed -e 's/ .*//' >${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz.sha256
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload hash
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz.sha256
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-darwin-amd64.tar.gz.sha256
          asset_content_type: text/plain

  # Build and pack the binaries for Windows.
  build_windows:
    runs-on: windows-latest
    needs: [create_release, vars]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out repository into the Go module directory
        uses: actions/checkout@v3

      - name: Select correct tag
        run: git checkout ${{ github.ref_name }}

      - name: Fetch repository dependencies
        run: go get -v -t ./...

      - name: Compile
        run: |
          go build -tags osusergo,netgo -ldflags="-extldflags=-static" -v -ldflags="-X github.com/${{ github.repository }}/cmd.ReleaseVersion=${{ needs.vars.outputs.release_version }}"
          choco install zip
          zip --junk-paths ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe.zip ${{ needs.vars.outputs.binary }}.exe
          $FileHash=(certutil -hashfile ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe.zip SHA256 | findstr /v hash | findstr /v SHA).replace(" ", "")
          echo "$FileHash" > ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe-zip.sha256

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe.zip
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe.zip
          asset_content_type: application/octet-stream

      - name: Upload hash
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe-zip.sha256
          asset_name: ${{ needs.vars.outputs.binary }}-${{ needs.vars.outputs.release_version }}-windows-exe-zip.sha256
          asset_content_type: text/plain
